# Generated by Django 5.2.5 on 2026-05-24 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leases", "0002_contracttemplate_delete_contracttemaplate_and_more"),
        ("property", "0002_alter_property_state_alter_property_zip_code"),
        ("users", "0007_alter_buyer_lead_type_alter_tenant_lead_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rent", "Rent Payment"),
                            ("security_deposit", "Security Deposit"),
                            ("late_fee", "Late Fee"),
                            ("maintenance_fee", "Maintenance Fee"),
                            ("commission_income", "Commission Income"),
                            ("other_income", "Other Income"),
                            ("utility_expense", "Utility Expense"),
                            ("maintenance_expense", "Maintenance Expense"),
                            ("property_tax_expense", "Property Tax Expense"),
                            ("commission_payout", "Commission Payout"),
                            ("advertising_expense", "Advertising Expense"),
                            ("other_expense", "Other Expense"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("online_portal", "Online Portal"),
                            ("other", "Other"),
                        ],
                        default="online_portal",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction Id from gateway or bank reference",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_income",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if this payment is an income (True) or an expense (False)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="leases.lease",
                    ),
                ),
                (
                    "real_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="property.property",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_financial_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments & Transactions",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="leases.lease",
                    ),
                ),
                (
                    "real_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="property.property",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="users.tenant",
                    ),
                ),
                (
                    "payments",
                    models.ManyToManyField(
                        blank=True, related_name="invoices_paid", to="finances.payment"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Invoices",
                "ordering": ["-due_date", "-created_at"],
            },
        ),
    ]
