stages:
  - lint
  - test
  # - security
  - build
  - deploy_staging
  - deploy_prod
  # - backend
  # - frontend-build

variables:
  CI_COMMIT_SHORT_SHA: master
  ENVIRONMENT: pipeline
  PYTHONUNBUFFERED: 1

default:
  interruptible: false
  cache:
    key: "node-pip-cache"
    paths:
      - backend/.cache/pip
      - backend/.venv/
      - frontend/node_modules
    policy: pull-push

# .default-rules:
#   rules:
#     - changes:
#       - .gitlab-ci.yml
backend-lint-job:
  stage: lint
  image: python:3.12
  extends:
    - .default-rules
  before_script:
    - cd backend
    - python -m venv .venv
    - source .venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Running isort..."
    - isort .
    - echo "Running black..."
    - black .
    - echo "Running flake8 linting..."
    - pip install flake8
    - flake8 --exclude .venv

frontend-lint-job:
  stage: lint
  image: node:20
  extends:
    - .default-rules
  before_script:
    - cd frontend
    - npm ci
  script:
    - echo "Running prettier check..."
    - npm run lint:format
    - echo "Running stylelint linting..."
    - npm run format --write
    - echo "Running eslint linting..."
    - npm run lint

backend-test-job:
  stage: test
  image: python:3.12
  extends:
    - .default-rules
  before_script:
    - cd backend
    - python -m venv .venv
    - source .venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py test

frontend-test-job:
  stage: test
  image: node:20
  extends:
    - .default-rules
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run test

Build-job:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--mtu=1460"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE/realestatemgt-backend:$CI_COMMIT_SHORT_SHA ./backend
    - docker build -t $CI_REGISTRY_IMAGE/realestatemgt-frontend:$CI_COMMIT_SHORT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/realestatemgt-backend:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/realestatemgt-frontend:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE/realestatemgt-backend:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/realestatemgt-backend:staging
    - docker tag $CI_REGISTRY_IMAGE/realestatemgt-frontend:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/realestatemgt-frontend:staging
    - docker push $CI_REGISTRY_IMAGE/realestatemgt-backend:staging
    - docker push $CI_REGISTRY_IMAGE/realestatemgt-frontend:staging
  only:
    - staging
  
# backend-security-job:
#   stage: security
#   image: python:3.12
#   extends:
#     - .default-rules
#   before_script:
#     - cd backend
#     - python -m venv .venv
#     - source .venv/bin/activate
#     - python -m pip install --upgrade pip
#     - pip install -r requirements.txt
#   script:
#     - bandit -r . -f json -o bandit-report.json --severity-level medium
#   artifacts:
#     paths:
#       - bandit-report.json

# frontend-security-job:
#   stage: security
#   image: node:20
#   extends:
#     - .default-rules
#   before_script:
#     - cd frontend
#     - npm ci
#   script:
#     - npm audit --audit-level=moderate

staging-job:
  stage: deploy_staging
  image: alpine:latest
  extends:
    - .default-rules
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p "$HOME/.ssh"
    - cp "$SSH_PRIVATE_KEY" "$HOME/.ssh/id_rsa"
    - chmod 600 "$HOME/.ssh/id_rsa"
    - ssh-keyscan -H "$SSH_HOST" >> "$HOME/.ssh/known_hosts"
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$STAGING_HOST "
      cd /app &&
      docker compose -f docker-compose.staging.yaml pull &&
      docker compose -f docker-compose.staging.yaml up -d
      "
  environment:
    name: staging
    url: http://$STAGING_HOST
  only:
    - staging

deploy-prod-job:
  stage: deploy_prod
  image: alpine:latest
  extends:
    - .default-rules
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p "$HOME/.ssh"
    - cp "$SSH_PRIVATE_KEY" "$HOME/.ssh/id_rsa"
    - chmod 600 "$HOME/.ssh/id_rsa"
    - ssh-keyscan -H "$SSH_HOST" >> "$HOME/.ssh/known_hosts"
  script:
    - ssh $SERVER_USER@$PROD_HOST "
      cd /app &&
      docker compose -f docker-compose.prod.yaml pull &&
      docker compose -f docker-compose.prod.yaml up -d
      "
  environment:
    name: production
    url: http://$PROD_HOST
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "push" && $CI_ENVIRONMENT_SLUG == "staging"'
      when: manual # requires human to click play
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "push" && $CI_ENVIRONMENT_SLUG == "production"'
      when: manual # requires human to click play

