image: python:3.12

pipelines:
  default:
    - step:
        name: Backend Tests
        services:
          - postgres
        caches:
          - pip
        script:
          - cd backend
          - export DJANGO_SETTINGS_MODULE=realestatemgt.settings
          - export ENVIRONMENT=pipeline
          - apt-get update && apt-get install -y default-mysql-client
          - until mysqladmin ping -h mysql -u root -proot --silent; do echo "Waiting for MySQL..."; sleep 2; done
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - python manage.py migrate
          - python manage.py test
    - step:
        name: Frontend Build
        image: node:20
        caches:
          - node
        script:
          - cd frontend
          - npm ci
          - npm run build

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: real_estate_test_db
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: Today123