image: python:3.12

pipelines:
  default:
    - step:
        name: Backend Tests
        services:
          - postgres
        caches:
          - pip
        script:
          - cd backend
          - export DJANGO_SETTINGS_MODULE=realestatemgt.settings
          - export ENVIRONMENT=pipeline
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - python manage.py migrate
          - python manage.py test
    - step:
        name: Frontend Build
        image: node:20
        caches:
          - node
        script:
          - cd frontend
          - npm ci
          - npm run build
