services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: real_estate_backend
    command: python manage.py runserver 0.0.0.0:8085
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8085"
    env_file:
      - ./backend/docker.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: real_estate_frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:15
    container_name: real_estate_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=real_estate_dev_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Today123

volumes:
  postgres_data: