# Generated by Django 5.2.5 on 2025-11-28 11:08

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.models.profile_image_upload_path,
            ),
        ),
    ]
