# Generated by Django 5.2.5 on 2026-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_leadstatus_remove_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="lead_type",
            field=models.CharField(
                blank=True,
                choices=[("buyer", "Buyer"), ("tenant", "Tenant")],
                default="buyer",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="lead_type",
            field=models.CharField(
                blank=True,
                choices=[("buyer", "Buyer"), ("tenant", "Tenant")],
                default="tenant",
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="LeadStatus",
        ),
    ]
