# Generated by Django 5.2.5 on 2026-04-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("property", "0002_alter_property_state_alter_property_zip_code"),
        ("users", "0007_alter_buyer_lead_type_alter_tenant_lead_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemaplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "template_content",
                    models.TextField(
                        help_text=(
                            "Use placeholders like {{ property.address }}, "
                            "{{ tenant.full_name }}, {{ lease.monthly_rent }} "
                            "for auto-population."
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lease_number", models.CharField(max_length=100, unique=True)),
                ("lease_type", models.CharField(max_length=50)),
                (
                    "lease_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DRAFT", "Draft"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("PENDING_TENANT", "Pending Approval"),
                            ("PENDING_SIGNATURE", "Pending Signature"),
                            ("RENEWED", "Renewed"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("lease_start_date", models.DateField()),
                ("lease_end_date", models.DateField()),
                ("rent_commencement_date", models.DateField()),
                ("lease_expiration_date", models.DateField()),
                ("lease_term_months", models.PositiveIntegerField()),
                ("notice_date", models.DateField(blank=True, null=True)),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rent_frequency", models.CharField(max_length=20)),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rent_schedule", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bill_code", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "late_fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "late_fee_grace_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tax_escalations", models.TextField(blank=True, null=True)),
                (
                    "operating_expense_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("lease_renewal_options", models.TextField(blank=True, null=True)),
                ("lease_termination_options", models.TextField(blank=True, null=True)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_leases",
                        to="users.agent",
                    ),
                ),
                (
                    "real_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="property.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease",
                "verbose_name_plural": "Leases",
                "ordering": ["-lease_start_date"],
            },
        ),
    ]
