# Generated by Django 5.2.5 on 2026-05-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0001_initial"),
        ("property", "0002_alter_property_state_alter_property_zip_code"),
        ("users", "0007_alter_buyer_lead_type_alter_tenant_lead_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "template_content",
                    models.TextField(
                        help_text="Use placeholders like {{ property.address }}, {{ tenant.full_name }}, {{ lease.monthly_rent }} for auto-population."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_template",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ContractTemaplate",
        ),
        migrations.AlterField(
            model_name="lease",
            name="real_property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease",
                to="property.property",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_tenant",
                to="users.tenant",
            ),
        ),
    ]
