# Generated by Django 5.2.5 on 2026-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="zip_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
